# Kezdet: Szabványos Flutter Podfile beállítás
require File.expand_path(File.join('..', 'flutter', 'generated_xcode_build_settings'), __FILE__)
file_path = File.expand_path(File.join('..', 'flutter', 'generated_xcode_build_settings'), __dir__)
require file_path if File.exist?(file_path)

# Ez tölti be a FLUTTER_ROOT útvonalat
if defined? FLUTTER_ROOT
  load File.join(FLUTTER_ROOT, 'packages', 'flutter_tools', 'bin', 'podhelper')
else
  # Biztonsági ellenőrzés, ha a generált beállítások hiányoznak
  warn "Flutter build settings not found. Ensure you have run 'flutter pub get'."
end
# Vége a beállításnak