class BeastIdezetek {
  static const List<String> lista = [
    "Gyúrj, vagy gyengülsz.",
    "A vas éhes. Etetned kell.",
    "Legyél állat, ne áldozat.",
    "Több súly, kevesebb pofázás.",
    "A fájdalom az edzés árnyéka.",
    "Törd össze a határaid.",
    "Nincs kifogás — csak súly.",
    "Menj, míg remeg a föld.",
    "A félelem nem emel. Te igen.",
    "A kegyelem nem része a programnak.",
    "Lélegezz. Emelj. Győzz.",
    "Az izomhoz küzdelem kell.",
    "Vér, izzadság, ismétlés.",
    "A gyengeséget kilélegezed.",
    "A vas nem fogja a kezed.",
    "Ez a te ketreced. Üvölts.",
    "Tedd le, és már emelnéd vissza.",
    "Nincs pihenő a csúcson.",
    "Az állatok nem panaszkodnak.",
    "Győzd le a tegnapi férget.",
    "Láncold magad a célhoz.",
    "A szörny benned lakik. Engedd ki.",
    "A fájdalom: upgrade.",
    "Lépj a csontjaidon át.",
    "A test tiltakozik, a lélek követeli.",
    "Égjen az izom.",
    "Csak az erő beszél.",
    "Még egy. Mindig még egy.",
    "A pokol kezdete: bemelegítés.",
    "A szörnyek építik az izmokat.",
    "Lépj ki emberként, gyere vissza vadállatként.",
    "A lusták sírnak, a vadak nyomnak.",
    "A súly a vallásod.",
    "Emelj úgy, mint akinek nincs holnap.",
    "Nehéz? Jó. Akkor működik.",
    "A tested fegyver. Töltsd újra.",
    "Izzadj, mint egy fenevad.",
    "A fájdalom haver.",
    "Törd meg a csendet — csattanjon a vas.",
    "A félelem könnyű. A vas nehéz.",
    "A test gyenge, a szörny éhes.",
    "A vérnyomásod a tapsod.",
    "Ne kérj engedélyt. Emelj.",
    "A súly nem könyörül.",
    "A legjobb állatok nem alszanak sokat.",
    "Rombold le a határaid.",
    "Szakítsd szét a gyengeséget.",
    "Emelj, míg nem marad kifogás.",
    "A vas a bíró.",
    "A fájdalom az evolúció ára.",
    "Adj bele mindent — vagy menj haza.",
    "A tested ordítson.",
    "Az izmaid kódolják át a sorsod.",
    "A szörnyek nem állnak meg.",
    "A lélek keményebb, mint a vas.",
    "Nincs “nem megy”. Csak “még egyszer”.",
    "A bestia dolgozik, amíg te alszol.",
    "Csak a ragadozók nőnek.",
    "Emeld fel a világod.",
    "A vas meghajlítja a jellemet.",
    "Égjen a tüdő.",
    "Gyúrj, amíg nem marad levegő.",
    "A fájdalom a tanár.",
    "Üsd vissza a gyengeséget.",
    "Izzadj, mint egy farkas a csatában.",
    "Az izmokért meg kell halni — képletesen.",
    "Légy az edzőterem ura.",
    "Nincs könnyű nap.",
    "A bestia benned tombol.",
    "Küzdj, mint egy megszállott.",
    "A kitartás a fegyvered.",
    "A célod a zsákmányod.",
    "A gyengeség csak egy mítosz.",
    "A súly nem hazudik — te se hazudj.",
    "A vér is izzadtság, csak drága.",
    "Róma sem épült kardio közben.",
    "A szörny nem pihen.",
    "A gyengeség csupán opció.",
    "Égesd fel a korlátaid.",
    "Emeld meg a saját gravitációd.",
    "A tested a csatatér.",
    "A vas az ellenség és a barát.",
    "Tépj ki minden kifogást.",
    "A pokolban nincs rest.",
    "A szörnyetet csak te eteted.",
    "A célod ordítson belőled.",
    "Az izom fáj — a büszkeség nem.",
    "Emeld túl magad.",
    "A szenvedés a bejárat.",
    "A siker az ellenséged képe.",
    "A bestia tanul.",
    "A tükör az ellenfél.",
    "A súly a terápia.",
    "Rombolj és építs egyszerre.",
    "A top nem elég — menj feljebb.",
    "A düh jó üzemanyag.",
    "A vas tiszta igazság.",
    "Kelj fel, szörny legyél.",
    "A testedet meghajlítod.",
    "A győzelem az izmokban lakik.",
    "Nincs kifogás, csak edzés.",
    "A vas nem hazudik.",
    "Minden ismétlés számít.",
    "Tedd meg ma, amit más nem.",
    "Légy erősebb, mint tegnap.",
    "A fájdalom csak jel, hogy fejlődsz.",
    "A tested a munkád eredménye.",
    "Kezd el, a többi jön magától.",
    "A kitartás győz.",
    "A lustaság nem épít izmokat.",
    "Ne add fel, amíg büszke nem leszel.",
    "A határaid csak a fejedben léteznek.",
    "Tedd oda magad!",
    "Az izzadtság: a győzelem üzemanyaga.",
    "A forma jön, ha maradsz.",
    "Az erő döntésekkel kezdődik.",
    "Csak csináld!",
    "Az eredmény a munkából születik.",
    "Ma is nyomnunk kell.",
    "A test követi az elmét.",
    "Nincs gyors megoldás, csak kemény munka.",
    "Dolgozz csöndben, mutass hangosan.",
    "A vas tiszteletet kér.",
    "A fejlődés nem véletlen.",
    "A ma fájdalma a holnap ereje.",
    "Tedd bele a melót!",
    "Már elkezdted – fejezd is be.",
    "Küzdj a legjobb verziódért.",
    "Nincs könnyű út.",
    "Minden nap egy új esély.",
    "A siker edzőcipőt visel.",
    "A vágy kevés, a tett számít.",
    "A gyengeség csak állapot, nem végzet.",
    "Légy jobb, ne tökéletes.",
    "Kezd kicsiben, de lépj nagyot.",
    "A fegyelem veri a motivációt.",
    "A tested a fegyvered.",
    "A fájdalom ideiglenes, az eredmény örök.",
    "Menj tovább akkor is, ha nem megy.",
    "Nem holnap, ma.",
    "Az izom nem ajándék.",
    "Lépj túl a komfortzónádon.",
    "Csináld úgy, mintha az életed múlna rajta.",
    "A vas nem sajnál.",
    "Erőt építesz, nem kifogást.",
    "A kitartás a kulcs mindenhez.",
    "Napi 1% is számít.",
    "A bajnokok a teremben születnek.",
    "A kihívás formál.",
    "A motiváció elmúlik, a fegyelem megmarad.",
    "Mindig van még egy ismétlés.",
    "A hangulat jön, az eredmény marad.",
    "Győzd le a tegnapi éned.",
    "A siker a részletekben lakik.",
    "A terhelés formálja az acélt.",
    "A nehéz út visz a csúcsra.",
    "A célodért edzel.",
    "Nincs lehetetlen, csak lassabb eredmény.",
    "A tested a tükröd.",
    "Ne panaszkodj, emelj.",
    "Ha nem izzadsz, nem dolgozol.",
    "A kitartásod lesz az erőd.",
    "A teremben mindenki egyenlő.",
    "Emelj szívvel, ne kifogással.",
    "A változás belül kezdődik.",
    "Csak menj be, a többi jön.",
    "A vas megmutatja, ki vagy.",
    "Szokássá teszed, nem kérdés.",
    "Az erő döntés kérdése.",
    "Küzdj, amíg szokássá lesz.",
    "A fegyelem hozza az eredményt.",
    "Az erő nem jön könnyen.",
    "A motiváció nem elég – dolgozz.",
    "A sikernek súlya van.",
    "Tedd meg magadért.",
    "Az izzadás a fejlődés ára.",
    "A formád rajtad múlik.",
    "Minden edzés számít.",
    "A céljaid nem teljesítik önmagukat.",
    "Dolgozz úgy, mint egy állat.",
    "Az akaraterő izmot épít.",
    "Ne állj meg, amíg kész nem vagy.",
    "Tedd bele, amit más nem tenne.",
    "A végeredmény a tetteid összege.",
    "A vas nem hazudik, a test se.",
    "A kényelem ellenség.",
    "Nem attól erősödsz, ami könnyű.",
    "A teremben nincs ego, csak munka.",
    "A tested befektetés.",
    "Jobb ma, mint holnap.",
    "A szokások formálnak.",
    "A sikeredért te felelsz.",
    "A célért szenvedni kell.",
    "A fejlődés lassú, de biztos.",
    "A kemény munka nem múlik el nyom nélkül.",
    "Az erő nem jön pihenésből.",
    "Ha könnyű, nem működik.",
    "Harcolj a célodért.",
    "A testépítés türelemjáték.",
    "A legnagyobb izom a kitartás."
  ];
}
